import Layout from '@/components/layout';
import { Button, Typography } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';

export default function Categories() {
  return (
    <Layout loading={false}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1">Categories</Typography>
    </Layout>
  );
}
