import Layout from '@/components/layout';
import { Typography } from '@mui/material';
import Head from 'next/head';

export default function Search() {
  return (
    <Layout loading={false}>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1">Search</Typography>
    </Layout>
  );
}
